CATEGORY_DICT = {
        'Fashion': ['Clothing (Brand)', 'Design & fashion', 'Jewelry/watches', 'Apparel & clothing',
                'Sunglasses & Eyewear Store', 'Hair Salon', 'Accessories', 'Shopping & retail', 'Retail company', 'Fashion Model'], 
        'Media': ['Actor', 'Digital creator', 'Musician', 'Artist', 'Designer', 'Art', 'Arts & entertainment', 'Performing Arts',
                'Photography Videography', 'DJ', 'Photographer', 'Video creator', 'Blogger', 'Comedian', 'Personal blog', 'Producer', 'Writer'], 
        'Health/Wellness': ['Health/beauty', 'Cycling Studio', 'Athlete', 'Vitamins/supplements', 'Medical & health', 'Coach', 'Fitness Model'], 
        'Food':['Restaurant'],
        'Electronics':['Electronics', 'Gamer'], 
        'Education': ['School', 'Education'],
        'Other': ['Home Improvement', 'Community', 'Just for fun', 'Scientist', 'Circus', 'Gardener', 'Pet Service', 'Government organization', 'Public figure', 'Not a business'], 
        'Business': ['Product/service', 'Local business', 'Entrepreneur'],
        'For Good':['Nonprofit organization', 'Youth Organization'], 
    }

# ['', 'Blogger', 'Video creator', 'Digital creator', 'Comedian',
#        'Personal blog', 'Scientist', 'Community', 'Circus', 'Artist',
#        'Producer', 'Writer', 'Designer', nan, 'Gardener', 'Entrepreneur',
#        'Athlete', 'Just for fun', 'Musician', 'Fitness Model',
#        'Fashion Model', 'Art', 'Arts & entertainment', 'Pet Service',
#        'Government organization', 'Health/beauty', 'Education',
#        'Performing Arts', 'Public figure', 'Photography Videography',
#        'Apparel & clothing', 'Gamer', 'Restaurant', 'Not a business'],